#!/bin/dash
# Creado por Termux Byte
atualizar='\033[1;32m'
echo "$Actualizando repositorios y terminal..."
apt update && upgrade -y
apt install -y wget
clear
k='\033[01;32m'
echo

echo "${k}.___________. _______ .______      .___  ___.  __    __  ___   ___         .______   ____    ____ .___________. _______ ";
echo "${k}|           ||   ____||   _  \     |   \/   | |  |  |  | \  \ /  /         |   _  \  \   \  /   / |           ||   ____|";
echo "${k}`---|  |----`|  |__   |  |_)  |    |  \  /  | |  |  |  |  \  V  /   ______ |  |_)  |  \   \/   /  `---|  |----`|  |__   ";
echo "${k}    |  |     |   __|  |      /     |  |\/|  | |  |  |  |   >   <   |______||   _  <    \_    _/       |  |     |   __|  ";
echo "${k}    |  |     |  |____ |  |\  \----.|  |  |  | |  `--'  |  /  .  \          |  |_)  |     |  |         |  |     |  |____  ";
echo "${k}    |__|     |_______|| _| `._____||__|  |__|  \______/  /__/ \__\         |______/      |__|         |__|     |_______|  ";
                                                                                                                        

echo
echo "Deseas instalar Ngrok? [Y/n]"
read opcao
case $opcao in
y)
echo
echo "Descargando Termux-ngrok..."
case `dpkg --print-architecture` in
aarch64)
    architectureURL="arm64" ;;
arm)
    architectureURL="arm" ;;
armhf)
    architectureURL="armhf" ;;
amd64)
    architectureURL="amd64" ;;
i*86)
    architectureURL="i386" ;;
x86_64)
    architectureURL="amd64" ;;
*)
    echo "Arquitetura desconocida"
esac

wget "https://github.com/tchelospy/NgrokTest/blob/master/ngrok-stable-linux-${architectureURL}.zip?raw=true" -O ngrok.zip
unzip ngrok.zip
cat ngrok > /data/data/com.termux/files/usr/bin/ngrok
chmod 700 /data/data/com.termux/files/usr/bin/ngrok
rm ngrok ngrok.zip
clear
echo
echo "Ejemplo para comprobar ngrok (ngrok http 80
@termuxbyte telegram)"
;;

n)
clear
echo "Ngrok instalado :("
echo
esac
