#!/bin/dash
# Creado por Termux Byte
atualizar='\033[1;32m'
echo "$Actualizando repositorios y terminal..."
apt update && upgrade -y
apt install -y wget
clear
k='\033[01;32m'
echo

echo "${k}||T ||||b ||||y ||||t ||||e || ";
echo "${k}||__||||__||||__||||__||||__|| ";
echo "${k}|/__\||/__\||/__\||/__\||/__\| ";

echo
echo "Deseas instalar Ngrok? [y/n]"
read opcao
case $opcao in
y)
echo
echo "Descargando Termux-ngrok..."
case `dpkg --print-architecture` in
aarch64)
    architectureURL="arm64" ;;
arm)
    architectureURL="arm" ;;
armhf)
    architectureURL="armhf" ;;
amd64)
    architectureURL="amd64" ;;
i*86)
    architectureURL="i386" ;;
x86_64)
    architectureURL="amd64" ;;
*)
    echo "Arquitetura desconocida"
esac

wget "https://github.com/tchelospy/NgrokTest/blob/master/ngrok-stable-linux-${architectureURL}.zip?raw=true" -O ngrok.zip
unzip ngrok.zip
cat ngrok > /data/data/com.termux/files/usr/bin/ngrok
chmod 700 /data/data/com.termux/files/usr/bin/ngrok
rm ngrok ngrok.zip
clear
echo
echo "Ejemplo para comprobar ngrok (ngrok http 80
@termuxbyte telegram)"
;;

n)
clear
echo "Ngrok instalado :("
echo
esac
